### ISSUE TITLE
show command has same ouput and dose not match readme

### ISSUE THREAD

**Issue by jsantarc** [maximilien/skills-tickets#1]
### Bug report

After generating a suggestion  list 
`/st.py suggestions list --credentials=./credentials.yml --show-details`
Found '468' suggestions
1. ID: '40393918', title: 'to make the site responsive', state: 'published'
2. ID: '40389799', title: 'Improve tests', state: 'published'
3. ID: '40382995', title: 'Improve on Website Loading Time', state: 'published'

I get the same output for each ID :
`st.py suggestions show 11569965 --credentials=./credentials.yml --show-details`
_Suggestion: 40393918 title: 'to make the site responsive' is currently 'published'
  referrer: https://courses.cognitiveclass.ai/courses/course-v1:SkillsNetwork+CB0105ENv1+2018/courseware/5adbf6a3d6d845499f6c40f53ef3b653/517cb8a5f13a47ceb0c44cb34e6599ba/
  vote_count: 1, subscriber_count: 1, comments_count: 0, supporters_count: 1
  category: Courses, status: None, response: None
  text: It is very very unresponsive_

`st.py suggestions show 11343366 --credentials=./credentials.yml --show-detai`

_Suggestion: 40393918 title: 'to make the site responsive' is currently 'published'
  referrer: https://courses.cognitiveclass.ai/courses/course-v1:SkillsNetwork+CB0105ENv1+2018/courseware/5adbf6a3d6d845499f6c40f53ef3b653/517cb8a5f13a47ceb0c44cb34e6599ba/
  vote_count: 1, subscriber_count: 1, comments_count: 0, supporters_count: 1
  category: Courses, status: None, response: None
  text: It is very very unresponsive_

**Comment by maximilien** [comment]
Hmm, thanks. Let me try to reproduce

**Comment by maximilien** [comment]
Good catch. Solved in last commit and release [v0.4.2](https://github.com/maximilien/skills-tickets/releases/tag/v0.4.2)
